/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panel;

import config.Config;
import entity.User;

/**
 *
 * @author ASUS
 */
public class ProfilePanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfilePAnel
     */
    public ProfilePanel() {
        initComponents();
    }
    public void fillUserComponents(){
         textAreaProfile.setText(Config.loggedInUser.getProfileDescription());
    }
public void fillUser(User user){
    user.setProfileDescription(textAreaProfile.getText());
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaProfile = new javax.swing.JTextArea();

        textAreaProfile.setColumns(20);
        textAreaProfile.setRows(5);
        jScrollPane2.setViewportView(textAreaProfile);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textAreaProfile;
    // End of variables declaration//GEN-END:variables
}
